---
title: "欧式空间的局部敏感哈希(LSH)理论与应用分享"
author: "bourneli"
date: "2016年10月"
output: 
  ioslides_presentation: 
    widescreen: yes
---



## 大纲

* 应用背景
* 计算方法
* 实现与优化


## 应用背景

在很多应用领域中，我们面对和需要处理的数据往往是海量并且具有很高的维度，怎样快速地从海量的高维数据集合中找到与某个数据最相似（距离最近）的一个数据或多个数据成为了一个难点和问题。

LSH主要解决**高纬度最邻近查找**问题，是一种**近似**算法，时间复杂度为**线性**，可大规模应用。应用场景举例：

1. 查找网络上的重复网页
2. 查找相似新闻网页或文章
3. 音乐检索
4. 指纹匹配
5. 图像检索

## 计算方法--核心思想

主要思路是设计一类hash函数，将那些比较类似的对象hash到一起，不同的对象的hash到不同的地方。hash过程相当于一种**过滤**机制，缩小检索范围。

最近邻居蛮力计算方法需要的时间复杂度$O(n^2)$，而使用LSH，可以在保证错误率很低的情况下，时间复杂度降到$O(n)$。在不需要准确最近邻居的应用场景，可以大规模应用，比如$n$达到亿级甚至更多。


## 计算方法--$(r_1,r_2,p_1,p_2)-sensitive$

定义：函数集合$H=\lbrace h: S \rightarrow U \rbrace$；任意向量$q,v \in S$；U是整数集合；$B(v,r) = \lbrace q \in X \| d(v,q) \le r \rbrace$，表示以点$v$为中心，距离为r范围内的所有点的集合。

$$
	如果 v \in B(q, r1), P(h(v)=h(q)) \ge p1 \\
	如果 v \notin B(q, r2), P(h(v)=h(q)) \le p2
$$

符合上述条件的函数h被称为$(r_1,r_2,p_1,p_2)-sensitive$。

直观解释就是将相距较近($r_1$以内)的向量hash到一起的概率要大($p_1$较接近1)；距离较远($r_2$以外，且$r_2 > r_1$)的对象hash到一起的概率小($p_2$较接近0)。


## 计算方法--欧式空间的LSH局部敏感函数

将n维向量随机射到一个向量，使用向量点乘，由于投射向量不是单位向量，所以严格意义上不能称之为投影。投射hash算法如下:

$$
	h(v) = \left\lfloor \frac{a \bullet v + b}{w} \right\rfloor
$$

其中

* $b \in [0,w]$是随机量，
* $a \in R^n,a_i \sim N(0,1)$，是被投射的向量。

$w$将投射结果严格的划分为不同的单位，$w$十分重要！

* 太大，较远的对象也设hash到一个单位里，计算量仍然十分大；
* 太小，很近的对象也无法hash到一起，导致找不到相似的对象。

## 计算方法--稳定分布

## 计算方法--常系数的概率密度变换

## 计算方法--欧式空间LSH局部敏感函数的碰撞概率分析

## 计算方法--碰撞概率单调性与参数估计

## 计算方法--w设置举例

## 计算方法--LSH加强

## 计算方法--桶的数量评估

## 应用于实践--计算流程总结

## 应用于实践 -- 踩坑总结

## 参考文献



